### ISSUE TITLE
Packaging on 4.25 fails

### ISSUE THREAD

**Issue by masterofshapes** [NinevaStudios/MqttUtilities-UnrealEngine#2]
Everything works in editor but when I package game I get a build error related to mqtt plugin. Was wondering if you had a version that works in 4.25 or if their is a way I can rebuild myself?

**Comment by tustanivsky** [comment]
Hello, please attach some error logs, so we can take a look. 

Also, in order to make MQTT plugin working in UE 4.25 you have to modify engine version in MqttUtilities.uplugin file (https://github.com/NinevaStudios/MqttUtilities-UnrealEngine/blob/master/MqttUtilities/MqttUtilities.uplugin) and place it in [ProjectRoot]/Plugins folder. Before launching your project remove Binaries, Build, Intermediate and Saved folders in [ProjectRoot] as well as Binaries and Intermediate folders in [ProjectRoot]/Plugins/MqttUtilities folder.

**Comment by masterofshapes** [comment]
Thanks that worked!
